// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParamKind } from "./ParamKind";

export type ParamSpec = { 
/**
 * the PowerShell parameter name, no leading dash (we add the `-` when we build argv).
 */
name: string, 
/**
 * what the form puts next to the input.
 */
label: string, kind: ParamKind, 
/**
 * starting value, as text. for a checkbox it's "true"/"false". empty means no default.
 */
default: string, 
/**
 * choices for a dropdown; ignored for every other kind.
 */
options: Array<string>, required: boolean, };
