// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One resolved parameter, ready to become argv. The frontend's param form builds these
 * from the filled-in values: `value: None` is a switch (just `-Name`), `Some` is
 * `-Name value`. A switch left off / an empty optional just isnt sent at all, so the
 * script's own `param()` default takes over.
 */
export type RunArg = { name: string, value: string | null, };
