// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunStatus } from "./RunStatus";

/**
 * One ordered event in a run's life. Important bit: output goes out as raw **chunks**,
 * not lines. a terminal wants the `\r`s, the half-lines and the ANSI left alone, and a
 * prompt printed without a trailing newline still has to reach the user — splitting on
 * newlines would break all of that.
 */
export type RunEvent = { "type": "started", run_id: number, interp: string, interp_version: string, pid: number, } | { "type": "stdout", run_id: number, chunk: string, } | { "type": "stderr", run_id: number, chunk: string, } | { "type": "exit", run_id: number, code: number | null, status: RunStatus, };
