// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A stored script, exactly as it lives in the table.
 */
export type Script = { id: number, name: string, description: string, tags: string, body: string, params_json: string, danger: string, created_at: string, updated_at: string, };
