// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the caller hands us to create or edit one. No id or timestamps — those are ours
 * to assign, not the frontend's.
 */
export type ScriptInput = { name: string, description: string, tags: string, body: string, params_json: string, danger: string, };
